# Generated by Django 3.2.9 on 2021-12-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('money', models.BigIntegerField()),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('processing', 'Moderatsiyada'), ('approved', 'Tasdiqlangan')], default='new', max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('degree', models.CharField(max_length=64, null=True)),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.university')),
            ],
        ),
    ]
