# Generated by Django 3.2.9 on 2021-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211213_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('processing', 'Moderatsiyada'), ('approved', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='new', max_length=64),
        ),
    ]
