# Generated by Django 3.2.9 on 2021-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sponsor_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='person_type',
            field=models.CharField(choices=[('physical', 'Jismoniy shaxs'), ('juridic', 'Yuridik shaxs')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='money',
            field=models.BigIntegerField(null=True),
        ),
    ]
