# Generated by Django 3.2.9 on 2021-12-15 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
